# Generated by Django 4.0.3 on 2023-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0004_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Blood_group',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
