# Generated by Django 4.0.3 on 2023-07-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0005_employee_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Blood_group',
            field=models.CharField(max_length=250),
        ),
    ]
